/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, June 8, 2021 at 2:39:10 PM Central Daylight Time
                       * Operating System: Version 14.7 (Build 18G5023c)
                       * Image Source: /usr/libexec/mobileactivationd
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


#import <mobileactivationd/mobileactivationd-Structs.h>
@interface GestaltHlpr : NSObject
+(id)getSharedInstance;
-(id)copyAnswer:(CFStringRef)arg1 ;
-(BOOL)getBoolAnswer:(CFStringRef)arg1 ;
-(void)addAGestaltKey:(CFStringRef)arg1 toDictionary:(id)arg2 required:(BOOL)arg3 errors:(id)arg4 ;
-(id)copyDeviceIDInfo:(id*)arg1 ;
-(id)copyDeviceInfo:(id*)arg1 ;
-(id)copyRegulatoryImagesInfo:(id*)arg1 ;
-(void)updateRecertInfo:(id)arg1 errors:(id*)arg2 ;
@end

