/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, June 8, 2021 at 2:39:10 PM Central Daylight Time
                       * Operating System: Version 14.7 (Build 18G5023c)
                       * Image Source: /usr/libexec/mobileactivationd
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


#import <mobileactivationd/mobileactivationd-Structs.h>
@class DataArk;

@interface MACollectionInterface : NSObject {

	BOOL _collectionLibraryLoaded;
	_SecKey* _signingKey;
	DataArk* _dark;

}

@property (readonly) _SecKey* signingKey;                               //@synthesize signingKey=_signingKey - In the implementation block
@property (assign,nonatomic) BOOL collectionLibraryLoaded;              //@synthesize collectionLibraryLoaded=_collectionLibraryLoaded - In the implementation block
@property (nonatomic,readonly) DataArk * dark;                          //@synthesize dark=_dark - In the implementation block
+(id)copyIngestURL;
-(id)initWithContext:(id)arg1 ;
-(void)dealloc;
-(_SecKey*)signingKey;
-(id)collectSigningAttestation:(id*)arg1 ;
-(id)collectSIK:(id*)arg1 ;
-(id)collectPCRT:(id*)arg1 ;
-(id)signingKeyPublicKeyWithError:(id*)arg1 ;
-(id)signatureForData:(id)arg1 error:(id*)arg2 ;
-(id)copyIngestHeaders:(id)arg1 withError:(id*)arg2 ;
-(id)copyIngestData:(id*)arg1 ;
-(BOOL)processSUInfo:(id)arg1 withError:(id*)arg2 ;
-(BOOL)collectionLibraryLoaded;
-(void)setCollectionLibraryLoaded:(BOOL)arg1 ;
-(DataArk *)dark;
@end

