/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, June 8, 2021 at 2:39:10 PM Central Daylight Time
                       * Operating System: Version 14.7 (Build 18G5023c)
                       * Image Source: /usr/libexec/mobileactivationd
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@protocol OS_dispatch_queue;
#import <mobileactivationd/mobileactivationd-Structs.h>
@class NSObject;

@interface MALog : NSObject {

	SCD_Struct_MA0* _logHandle;
	NSObject*<OS_dispatch_queue> _queue;

}

@property (assign,nonatomic) SCD_Struct_MA0* logHandle;                       //@synthesize logHandle=_logHandle - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;              //@synthesize queue=_queue - In the implementation block
+(id)getSharedInstance;
-(id)init;
-(void)dealloc;
-(void)deleteExpiredLogFiles;
-(void)logMessage:(id)arg1 toSyslog:(BOOL)arg2 ;
-(SCD_Struct_MA0*)logHandle;
-(void)setLogHandle:(SCD_Struct_MA0*)arg1 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
@end

