/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, June 8, 2021 at 2:39:10 PM Central Daylight Time
                       * Operating System: Version 14.7 (Build 18G5023c)
                       * Image Source: /usr/libexec/mobileactivationd
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */

typedef struct {
	void field1;
	char* field2;
	char* field3;
	long long field4;
	unsigned field5;
	int field6;
	int field7;
	int field8;
	int field9;
} SCD_Struct_MA0;

typedef struct __CFString* CFStringRef;

typedef struct NACContextOpaque_* NACContextOpaque_Ref;

typedef struct PSCSessionInternal_* PSCSessionInternal_Ref;

