/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, June 8, 2021 at 2:39:10 PM Central Daylight Time
                       * Operating System: Version 14.7 (Build 18G5023c)
                       * Image Source: /usr/libexec/mobileactivationd
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@protocol MobileActivationProtocol <NSObject>
@required
-(void)getActivationStateWithCompletionBlock:(/*^block*/id)arg1;
-(void)copyRTCResetCountWithCompletionBlock:(/*^block*/id)arg1;
-(void)copyMonotonicClockWithCompletionBlock:(/*^block*/id)arg1;
-(void)createTunnel1ActivationInfo:(id)arg1 options:(id)arg2 withCompletionBlock:(/*^block*/id)arg3;
-(void)createTunnel1SessionInfoWithCompletionBlock:(/*^block*/id)arg1;
-(void)createActivationInfoWithCompletionBlock:(/*^block*/id)arg1;
-(void)handleActivationInfo:(id)arg1 withCompletionBlock:(/*^block*/id)arg2;
-(void)copyUCRTWithCompletionBlock:(/*^block*/id)arg1;
-(void)copyPCRTTokenWithCompletionBlock:(/*^block*/id)arg1;
-(void)isDeviceBrickedWithCompletionBlock:(/*^block*/id)arg1;
-(void)deactivateDeviceWithCompletionBlock:(/*^block*/id)arg1;
-(void)requestDeviceReactivationWithCompletionBlock:(/*^block*/id)arg1;
-(void)getActivationBuildWithCompletionBlock:(/*^block*/id)arg1;
-(void)copyActivationRecordWithCompletionBlock:(/*^block*/id)arg1;
-(void)unbrickDeviceWithCompletionBlock:(/*^block*/id)arg1;
-(void)recertifyDeviceWithCompletionBlock:(/*^block*/id)arg1;
-(void)handleActivationInfoWithSession:(id)arg1 activationSignature:(id)arg2 completionBlock:(/*^block*/id)arg3;
-(void)issueClientCertificateLegacy:(id)arg1 WithCompletionBlock:(/*^block*/id)arg2;
-(void)issueClientCertificateWithReferenceKey:(id)arg1 options:(id)arg2 completion:(/*^block*/id)arg3;
-(void)isInFieldCollectedWithCompletionBlock:(/*^block*/id)arg1;
-(void)updateBasebandTicket:(id)arg1 baaCertData:(id)arg2 baaIntermediateCert:(id)arg3 options:(id)arg4 withCompletionBlock:(/*^block*/id)arg5;
-(void)getDCRTStateWithCompletionBlock:(/*^block*/id)arg1;
-(void)copyDCRTWithCompletionBlock:(/*^block*/id)arg1;
-(void)issueDCRT:(id)arg1 withCompletionBlock:(/*^block*/id)arg2;

@end

