/*
                       * This header is generated by classdump-dyld 1.5
                       * on Tuesday, June 8, 2021 at 2:39:10 PM Central Daylight Time
                       * Operating System: Version 14.7 (Build 18G5023c)
                       * Image Source: /usr/libexec/mobileactivationd
                       * classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos. Updated by Kevin Bradley.
                       */


@protocol OS_dispatch_queue;
#import <mobileactivationd/mobileactivationd-Structs.h>
@class DataArk, NSObject;

@interface MobileRecertifyEngine : NSObject {

	DataArk* _dark;
	NSObject*<OS_dispatch_queue> _queue;

}

@property (nonatomic,retain) DataArk * dark;                                  //@synthesize dark=_dark - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;              //@synthesize queue=_queue - In the implementation block
-(id)initWithQueue:(id)arg1 dark:(id)arg2 ;
-(id)createRecertInfoWithDataArk:(id)arg1 alcoholBlob:(NACContextOpaque_Ref)arg2 options:(id)arg3 error:(id*)arg4 ;
-(void)recertifyDevice:(/*^block*/id)arg1 ;
-(DataArk *)dark;
-(void)setDark:(DataArk *)arg1 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
@end

